// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozonva/ova-journey-api/internal/metrics (interfaces: Metrics)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// CreateJourneyCounterInc mocks base method.
func (m *MockMetrics) CreateJourneyCounterInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateJourneyCounterInc")
}

// CreateJourneyCounterInc indicates an expected call of CreateJourneyCounterInc.
func (mr *MockMetricsMockRecorder) CreateJourneyCounterInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJourneyCounterInc", reflect.TypeOf((*MockMetrics)(nil).CreateJourneyCounterInc))
}

// DeleteJourneyCounterInc mocks base method.
func (m *MockMetrics) DeleteJourneyCounterInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteJourneyCounterInc")
}

// DeleteJourneyCounterInc indicates an expected call of DeleteJourneyCounterInc.
func (mr *MockMetricsMockRecorder) DeleteJourneyCounterInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJourneyCounterInc", reflect.TypeOf((*MockMetrics)(nil).DeleteJourneyCounterInc))
}

// MultiCreateJourneyCounterInc mocks base method.
func (m *MockMetrics) MultiCreateJourneyCounterInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MultiCreateJourneyCounterInc")
}

// MultiCreateJourneyCounterInc indicates an expected call of MultiCreateJourneyCounterInc.
func (mr *MockMetricsMockRecorder) MultiCreateJourneyCounterInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiCreateJourneyCounterInc", reflect.TypeOf((*MockMetrics)(nil).MultiCreateJourneyCounterInc))
}

// UpdateJourneyCounterInc mocks base method.
func (m *MockMetrics) UpdateJourneyCounterInc() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateJourneyCounterInc")
}

// UpdateJourneyCounterInc indicates an expected call of UpdateJourneyCounterInc.
func (mr *MockMetricsMockRecorder) UpdateJourneyCounterInc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateJourneyCounterInc", reflect.TypeOf((*MockMetrics)(nil).UpdateJourneyCounterInc))
}
