// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozonva/ova-journey-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozonva/ova-journey-api/internal/models"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddJourneys mocks base method.
func (m *MockRepo) AddJourneys(arg0 []models.Journey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddJourneys", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddJourneys indicates an expected call of AddJourneys.
func (mr *MockRepoMockRecorder) AddJourneys(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddJourneys", reflect.TypeOf((*MockRepo)(nil).AddJourneys), arg0)
}

// DescribeJourney mocks base method.
func (m *MockRepo) DescribeJourney(arg0 uint64) (*models.Journey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeJourney", arg0)
	ret0, _ := ret[0].(*models.Journey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeJourney indicates an expected call of DescribeJourney.
func (mr *MockRepoMockRecorder) DescribeJourney(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeJourney", reflect.TypeOf((*MockRepo)(nil).DescribeJourney), arg0)
}

// ListJourneys mocks base method.
func (m *MockRepo) ListJourneys(arg0, arg1 uint64) ([]models.Journey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJourneys", arg0, arg1)
	ret0, _ := ret[0].([]models.Journey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJourneys indicates an expected call of ListJourneys.
func (mr *MockRepoMockRecorder) ListJourneys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJourneys", reflect.TypeOf((*MockRepo)(nil).ListJourneys), arg0, arg1)
}
