version: "3.9"

services:
  ova-journey-api:
    container_name: ova-journey-api
    build: .
    restart: unless-stopped
    depends_on:
      - database
      - jaeger
      - kafka
    networks:
      - ova-journey-api-network
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ova-journey-api
    ports:
      - "8080:8080" # JSON gateway (+SwaggerUI on path /swagger)
      - "8081:8081" # gRPC service
      - "9100:9100" # gRPC metrics Prometheus

  database:
    image: postgres:13
    restart: unless-stopped
    networks:
      - ova-journey-api-network
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ova-journey-db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ova_journey_api

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    networks:
      - ova-journey-api-network
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ova-journey-jaeger
    ports:
      - "6831:6831"
      - "16686:16686"


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    networks:
      - ova-journey-api-network
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ova-journey-zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - ova-journey-api-network
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ova-journey-kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - ova-journey-api-network
    ports:
      - "8082:8082"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - SERVER_PORT=8082

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    depends_on:
      - ova-journey-api
    networks:
      - ova-journey-api-network
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    networks:
      - ova-journey-api-network

  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    networks:
      - ova-journey-api-network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.1
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - ova-journey-api-network
    ports:
      # Graylog web interface and REST API
      - "9000:9000"
      # Syslog TCP
      - "1514:1514"
      # Syslog UDP
      - "1514:1514/udp"
      # GELF TCP
      - "12201:12201"
      # GELF UDP
      - "12201:12201/udp"
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/

networks:
  ova-journey-api-network:
    driver: bridge