version: "3.9"

services:
  ova-journey-api:
    container_name: ova-journey-api
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - database

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ova_journey_api
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data