version: "3.9"

services:
  ova-journey-api:
    container_name: ova-journey-api
    build: .
    restart: unless-stopped
    depends_on:
      - database
      - jaeger
      - kafka
    networks:
      - ova-journey-api-network
    ports:
      - "8080:8080"
      - "9090:9090"

  database:
    image: postgres:13
    restart: unless-stopped
    networks:
      - ova-journey-api-network
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ova_journey_api

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    networks:
      - ova-journey-api-network
    ports:
      - "6831:6831"
      - "16686:16686"


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: unless-stopped
    networks:
      - ova-journey-api-network
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    restart: unless-stopped
    depends_on:
      - zookeeper
    networks:
      - ova-journey-api-network
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    restart: unless-stopped
    depends_on:
      - kafka
    networks:
      - ova-journey-api-network
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - SERVER_PORT=9093

networks:
  ova-journey-api-network:
    driver: bridge