project:
  name: Journey API for Amazon Voice Assistant Project
  version: v0.0.0-test

grpc:
  host: 127.0.0.1
  port: 9090

gateway:
  host: 127.0.0.1
  port: 8080

database:
  host: database
  port: 5432
  user: postgres
  password: postgres
  name: ova_journey_api
  sslMode: disable
  driver: pgx

chunkSize: 2

jaeger:
  host: jaeger
  port: 6831

kafka:
  topic: "ova-journey-api"
  brokers:
    - "kafka:9092"

prometheus:
  host: 0.0.0.0
  port: 9100
  path: "/metrics"